[package]
name = "gophsters"
version = "0.1.0"
authors = ["Julien Blanchard <julien@sideburns.eu>"]

[dependencies]
hyper = "0.12"
hyper-tls = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
chrono = "*"
regex ="*"
textwrap ="*"
deunicode = "0.4.0"